# ---- PROBLEM 2 ---- #

# Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
#
# 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
#
# By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

# ---- --------- ---- #


#assign start values
max_value = 4_000_000
previous_fibo, current_fibo = 1, 1
sum = 0

#run loop to generate fibos and add even fibos to sum
while current_fibo < max_value
  sum += current_fibo if current_fibo.even?
  previous_fibo, current_fibo = current_fibo, current_fibo + previous_fibo
end

#print result
puts sum